version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies into application bundle"
      - pip install --upgrade pip
      - pip install -r requirements.txt -t .

artifacts:
  files:
    - '**/*'
